### PR TITLE
Fix The SEO Framework (autodescription) settings

### PR DESCRIPTION
**Pull request by timiwahalahti**
As discussed, we are planning to switch Yoast SEO back to The SEO Framework as our default plugin for the job. One of the requirements that needed to be addressed before the change, as modifying some functionalities of The SEO Framework.

Unfortunately, the plugin lacks proper filters to modify which features are in use. But it provides a way to change the default settings for the plugin, so let's use that opportunity then.

We disable the SEO bar on listings, character counter and set the plugin to remove term type prefixes from generated archive titles. This is done when the user clicks the "Reset settings" button on the SEO settings page.

There's no easy way to do the reset programmatically, so we show an admin notice if the reset hasn't been done. Notice is cleared after The SEO Framework has called filter `the_seo_framework_default_site_options`.

Production sites running The SEO Framework are unaffected, as there's feature pinning check that will activate the notice only if Air helper has been activated after the version when this feature is introduced.

### CODE REVIEW

**Comment by ronilaukkarinen** [comment]
Can you provide steps to test it out? I have airdev.test project set up with latest autodescription and air-helper, with air-helper fetched to this PR changes:

```
git fetch origin
git checkout -b fix/autodescription-settings origin/fix/autodescription-settings
```

Yet I see no changes in autodescription or post listings? What is confusing to me is why reset is needed and what this PR will bring to the table as now visible changes are shown after activation - please note I may be doing something wrong as well so guide me.

Still quite hesitant to this move because of the lack of features needed for good SEO content creation, for instance as far as I know of there is not **any kind** of content analysis features in SEO Framework, it's still way too stripped down. I mean of course this feature in Yoast that have that have helped me and some our customers tremendously in the past while creating new content:

Screen-Shot-2021-02-19-11-30-51 94

But I guess it's "In Progress", although has been from 2018 like [this issue](https://github.com/sybrew/the-seo-framework/issues/108) shows. Some pondering [on forums](https://wordpress.org/support/topic/no-usage-of-focus-keywords-2/) about this as well.

But, again, Yoast users will not need to switch and obviously most of our clients won't be using SEO features anyway so for new projects "some kind of plugin" is good to have for that so still my other foot is in the default-camp here. Although it gets easily frustrated to hear "can we switch to Yoast" and do the switching all day long for new customers. I'm not saying it has been that way but many sites did the transformation nevertheless. Better to have this discussion sooner or later.

**Comment by timiwahalahti** [comment]
> Can you provide steps to test it out? 

You probably have air helper installed and thus there's nothing visible on your dev env. As stated, this change will have an effect only on new sites that do not have air helper enabled.

For testing purposed, you can remove the `air_helper_activated_at_version` option from the options table.

After removing that option, you should see a notice that suggests user reset their The SEO Framework settings. The reset can be done from the top of the SEO settings page. After the reset notice should be gone, the option "Display the SEO Bar in overview tables?" unchecked, the option "Display character counters?" unchecked and the option "Remove term type prefixes from generated archive titles?" checked under prefix tab in title settings. As a most noticeable change, you shouldn't see the annoying traffic lights bar on post/page listings.

> What is confusing to me is why reset is needed

Because, as stated, The SEO Framework does not provide filters to change the appearance of features during runtime. We need to change the settings in order to disable some features we don't like. But we can change the plugin's own default settings with filter - and these default settings are put to place during the reset.

As the admin notice says, the reset should be done only if manual changes haven't been yet made to the settings. Meaning that the reset needs to be done right after activating the plugin preferably.

If we'd have an opportunity to run the reset automatically right after activation or filters to change the behaviour during runtime - I'd have done that. In this situation, the PR's solution with manual reset is a good middle solution on modifying the behaviour to our preferences without the need to manually change every setting.

> Still quite hesitant to this move because of the lack of features needed for good SEO content creation, for instance as far as I know of there is not any kind of content analysis features in SEO Framework, it's still way too stripped down. 

To be honest, I thought we already covered this discussion on ou dev retreat and ended up at the conclusion that The SEO Framework would be default as most of the clients don't leverage and/or even need all the features provided by Yoast. For most of the clients, they just need an easy way to set content for search engines and of tags - which TSF handles quite nicely with simple UI. I thought we also agreed that for the clients/projects that do want Yoast or are blog/news centric, we'll switch to Yoast right at the beginning of the project.

That conversation is out of scope for this PR, but I'm happy to continue the debate elsewhere :)

**Comment by ronilaukkarinen** [comment]
Thanks for these. Will re-review soon.

> I thought we also agreed that for the clients/projects that do want Yoast or are blog/news centric, we'll switch to Yoast right at the beginning of the project.

Correct. Just wanted to state out these related to our dev-retreat discussion for the record nevertheless to fill the blanks in my still ongoing insecurities, haha. Good point about the blog centricity, classic blogger perspective speaking here. So never mind about some of my ramblings, I'm actually happy for the cleaner instances in the future.

**Comment by ronilaukkarinen** [comment]
For some reason after removing `air_helper_activated_at_version` option from the options table and reactivating air-helper I don't see any notice or changes. I made sure air-helper is from this branch by downloading the zip and replacing the folder. The version number on this branch still seems to be 2.5.0, is this a problem?

**Comment by ronilaukkarinen** [comment]
Confirmed working without version check. Feel free to merge @timiwahalahti.

**Pull request merged**
